package se.davidmagnusson.devourerofbricks.activities;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Point;
import android.os.Bundle;
import android.util.Log;
import android.view.Display;
import android.view.ViewGroup;

import se.davidmagnusson.devourerofbricks.gameengine.GameView;
import se.davidmagnusson.devourerofbricks.helpers.FX;
import se.davidmagnusson.devourerofbricks.helpers.FontReplacer;
import se.davidmagnusson.devourerofbricks.services.MusicPlayerService;

/**
 * Here is where the games take place. It uses a own View that extends the SurfaceView class
 * to run the game in.
 */

public class GameActivity extends Activity {

    GameView gameView;

    /**
     * Initialing the gameView and setting it to the content view
     *
     * @param savedInstanceState autogenerated by android
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //Get the screens resolution
        Display display = getWindowManager().getDefaultDisplay();
        Point size = new Point();
        display.getRealSize(size);

        gameView = new GameView(this, getIntent().getByteExtra("level", (byte) 1), size.x, size.y);
        setContentView(gameView);

        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "create");
        intent.putExtra("song", "music/ingame.mp3"); //TODO change song
        startService(intent);
    }

    /**
     * Same as super just added a call to the gameViews onResume and starts the music and fx
     */
    @Override
    protected void onResume() {
        super.onResume();
        gameView.onResume();
        FX.initFX(getApplicationContext());
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "resume");
        startService(intent);
    }

    /**
     * Same as super just added a call to the gameViews onPause and pauses fx and music
     */
    @Override
    protected void onPause() {
        super.onPause();
        gameView.onPause();
        FX.releaseSound();
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "pause");
        startService(intent);
    }
}
