package se.davidmagnusson.devourerofbricks.activities;

import android.app.Activity;
import android.graphics.Point;
import android.os.Bundle;
import android.util.Log;
import android.view.Display;
import android.view.ViewGroup;

import se.davidmagnusson.devourerofbricks.gameengine.GameView;
import se.davidmagnusson.devourerofbricks.helpers.FontReplacer;

/**
 * Here is where the games take place. It uses a own View that extends the SurfaceView class
 * to run the game in.
 */

public class GameActivity extends Activity {

    GameView gameView;

    /**
     * Initialing the gameView and setting it to the content view
     *
     * @param savedInstanceState autogenerated by android
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //Get the screens resolution
        Display display = getWindowManager().getDefaultDisplay();
        Point size = new Point();
        display.getRealSize(size);

        gameView = new GameView(this, getIntent().getByteExtra("level", (byte) 1), size.x, size.y);
        setContentView(gameView);
    }

    /**
     * Same as super just added a call to the gameViews onResume
     */
    @Override
    protected void onResume() {
        super.onResume();
        gameView.onResume();
    }

    /**
     * Same as super just added a call to the gameViews onPause
     */
    @Override
    protected void onPause() {
        super.onPause();
        gameView.onPause();
    }
}
