package se.davidmagnusson.devourerofbricks.activities;

import android.app.Activity;
import android.content.Intent;
import android.databinding.DataBindingUtil;
import android.graphics.Typeface;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.ViewGroup;

import se.davidmagnusson.devourerofbricks.R;
import se.davidmagnusson.devourerofbricks.databinding.LevelSelectionLayoutBinding;
import se.davidmagnusson.devourerofbricks.helpers.FontReplacer;
import se.davidmagnusson.devourerofbricks.services.MusicPlayerService;
import se.davidmagnusson.devourerofbricks.viewmodels.LevelSelectionViewModel;

/**
 * This is the activity where the player selects which level it wants to play.
 * Uses a viewmodel see viewmodels -> LevelSelectionViewModel.
 */
public class LevelSelectionActivity extends Activity {

    /**
     * This method is called when this activity is started by an intent and android is building it.
     * Also changes the font.
     * @param savedInstanceState auto generated by android.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        LevelSelectionViewModel viewModel = new LevelSelectionViewModel(this);
        LevelSelectionLayoutBinding binding = DataBindingUtil.setContentView(this, R.layout.level_selection_layout);
        binding.setViewmodel(viewModel);

        FontReplacer.setAppFont((ViewGroup) findViewById(android.R.id.content).getRootView(),
                Typeface.createFromAsset(getAssets(), "fonts/Gamegirl.ttf"),
                false);
    }

    /**
     * This is also called by android when resumes this application and it resumes the music
     */
    @Override
    protected void onResume() {
        super.onResume();
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "resume");
        startService(intent);

    }

    /**
     * This method is auto called by android when something interrupts the application (the user
     * press the home button, a text message...), this pauses the music.
     */
    @Override
    protected void onPause() {
        super.onPause();
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "pause");
        startService(intent);
    }
}
