package se.davidmagnusson.devourerofbricks.activities;

import android.app.Activity;
import android.content.Intent;
import android.databinding.DataBindingUtil;
import android.graphics.Typeface;
import android.os.Bundle;
import android.support.v7.app.AlertDialog;
import android.support.v7.view.ContextThemeWrapper;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import com.google.android.gms.ads.AdRequest;
import com.google.android.gms.ads.AdView;
import com.google.android.gms.ads.MobileAds;

import se.davidmagnusson.devourerofbricks.R;
import se.davidmagnusson.devourerofbricks.databinding.LevelSelectionLayoutBinding;
import se.davidmagnusson.devourerofbricks.helpers.FX;
import se.davidmagnusson.devourerofbricks.helpers.FontReplacer;
import se.davidmagnusson.devourerofbricks.services.MusicPlayerService;
import se.davidmagnusson.devourerofbricks.viewmodels.LevelSelectionViewModel;

/**
 * This is the activity where the player selects which level it wants to play.
 * Uses a viewmodel see viewmodels -> LevelSelectionViewModel.
 */
public class LevelSelectionActivity extends Activity {

    /**
     * This method is called when this activity is started by an intent and android is building it.
     * Also changes the font.
     * @param savedInstanceState auto generated by android.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        LevelSelectionViewModel viewModel = new LevelSelectionViewModel(this);
        LevelSelectionLayoutBinding binding = DataBindingUtil.setContentView(this, R.layout.level_selection_layout);
        binding.setViewmodel(viewModel);

        MobileAds.initialize(getApplicationContext(), getString(R.string.level_selection_banner_ad_unit_id));
        AdView ad = (AdView) findViewById(R.id.level_selection_banner_ad);
        AdRequest adReq = new AdRequest.Builder().build();
        ad.loadAd(adReq);

        FontReplacer.setAppFont((ViewGroup) findViewById(android.R.id.content).getRootView(),
                Typeface.createFromAsset(getAssets(), "fonts/EarlyGameBoy.ttf"),
                false);

        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "create");
        intent.putExtra("song", "music/first.mp3");
        startService(intent);
    }

    /**
     * This is also called by android when resumes this application and it resumes the music
     */
    @Override
    protected void onResume() {
        super.onResume();
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "resume");
        startService(intent);

    }

    /**
     * This method is auto called by android when something interrupts the application (the user
     * press the home button, a text message...), this pauses the music, and tells the FX that
     * this activity is shutting down
     */
    @Override
    protected void onPause() {
        super.onPause();
        FX.releaseSound();
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "pause");
        startService(intent);
    }

    public void testClick(View inView){
        AlertDialog.Builder builder = new AlertDialog.Builder(new ContextThemeWrapper(this, R.style.AppTheme));
        LayoutInflater inflater = LayoutInflater.from(this);
        View view = inflater.inflate(R.layout.level_how_to_play, null);
        Button button = (Button) view.findViewById(R.id.level_how_to_play_button);

        FontReplacer.setAppFont((ViewGroup) view.getRootView(),
                Typeface.createFromAsset(getAssets(), "fonts/EarlyGameBoy.ttf"),
                false);

        builder.setCancelable(false);
        builder.setView(view);

        final AlertDialog showDialog = builder.create();

        button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                showDialog.dismiss();
            }
        });

        showDialog.show();
    }
}
