package se.davidmagnusson.devourerofbricks.activities;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Typeface;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup;

import se.davidmagnusson.devourerofbricks.R;
import se.davidmagnusson.devourerofbricks.helpers.FX;
import se.davidmagnusson.devourerofbricks.helpers.FontReplacer;
import se.davidmagnusson.devourerofbricks.services.MusicPlayerService;


/**
 * The Main menu activity, no viewmodel here because it's only 3 static buttons.
 */
public class MainMenuActivity extends Activity {

    /**
     * This is the onCreate method that android uses when this activity is building,
     * also inits the music player
     * @param savedInstanceState auto generated by android.
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.main_menu_layout);

        FX.initFX(this.getApplication().getApplicationContext());

        final Typeface mFont = Typeface.createFromAsset(getAssets(), "fonts/EarlyGameBoy.ttf");
        final ViewGroup mContainer = (ViewGroup) findViewById(android.R.id.content).getRootView();
        FontReplacer.setAppFont(mContainer, mFont, false);

        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "create");
        intent.putExtra("song", "music/first.mp3");
        startService(intent);
    }

    /**
     * This is auto called by android when it's resumed, starts the music again
     */
    @Override
    protected void onResume() {
        super.onResume();
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "resume");
        startService(intent);
    }

    /**
     * This is auto called by android when it's paused, pauses the music
     */
    @Override
    protected void onPause() {
        super.onPause();
        Intent intent = new Intent(this, MusicPlayerService.class);
        intent.putExtra("action", "pause");
        startService(intent);

    }

    /**
     * This methd is called when the player presses the play button in the main menu.
     * It starts the LevelSelectionActicity and plays button pressed sound.
     * @param v the view that was pressed, auto sent by android
     */
    public void playButtonClicked(View v){
        FX.play(FX.menuButtonClicked, 1, 1, 0, 0, 1);
        Intent intent = new Intent(this, LevelSelectionActivity.class);
        startActivity(intent);
    }
}
